version: '3'

services:
  # Database
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mysql_root
      UPLOAD_LIMIT: 9999999
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:php8.1
    ports:
      - '8000:80'
      - '9003:9003'
    restart: always
    volumes: ['./terraform/docker/html:/var/www/html']
    environment:
      WORDPRESS_ENV: 'local'
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_ENVIRONMENT_TYPE', 'local' );
        define( 'WP_HOME', 'http://localhost:8000' );
        define( 'WP_SITEURL', 'http://localhost:8000' );
        define( 'WP_DEBUG', true );
        define( 'WP_DEBUG_LOG', true );
    env_file:
      - ./.env
  # Redis
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
volumes:
  wordpress:
  db:
  phpmyadmin:
  cache:
